### ISSUE TITLE
How to set pNext

### ISSUE THREAD

**Issue by Reon90** [maierfelix/nvk#6]
There is opportunity to set pNext in this way?

```
VkPhysicalDeviceFeatures2 features2 = { };
features2.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2;

VkDeviceCreateInfo deviceCreateInfo;
deviceCreateInfo.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
deviceCreateInfo.pNext = &features2;
```

**Comment by maierfelix** [comment]
pNext is ignored at the moment, but I will gladly remove this limitation

**Comment by Reon90** [comment]
@maierfelix could you please estimate, how long does it take?

**Comment by maierfelix** [comment]
I will try to cover this as soon as possible, could you send me another (more specific) example of your needs?

**Comment by Reon90** [comment]
@maierfelix 
`
        let RTProps = new VkPhysicalDeviceRayTracingPropertiesNV();
        RTProps.maxRecursionDepth = 0;
        RTProps.shaderGroupHandleSize = 0;

        let devProps = new VkPhysicalDeviceProperties2();
        devProps.pNext = RTProps;

        VkGetPhysicalDeviceProperties2(PhysicalDevice, devProps);
`
I try to use it to implement RT example.

**Comment by maierfelix** [comment]
Awesome, I will give my best to have a fix for this soon

**Comment by maierfelix** [comment]
Enabled `pNext` member in commit https://github.com/maierfelix/nvk/commit/28ccc03de19f82c7f1eb4ec08c551fe6d3ba9adb
Type reflection isn't supported yet for pNext members, but this is only a limitation if you want to read back types like arrays or nested objects. `VkPhysicalDeviceRayTracingPropertiesNV` only contains numeric members, so this should work for you.

Unfortunately I cannot test your case, since I don't have an RTX card. If you want to test the commit, then just clone master and approve that it works for you.

**Comment by Reon90** [comment]
@maierfelix thank you, It was fixed.
